from .easy_mobile_sam import NODE_CLASS_MAPPINGS as MOBILE_SAM_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MOBILE_SAM_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**MOBILE_SAM_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MOBILE_SAM_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
